### ISSUE TITLE
(Resolved) Flashing with new firmware_mini.bin, but no wireless nw after bootup?

### ISSUE THREAD

**Issue by jroux1** [letscontrolit/ESPEasy-platformio#1]
Hello, wanted to put my foot into the water with the new platformio business, bit strange to us older ESPEasy & Arduino compile guys...

I downloaded the firmware_mini.bin, and flashed it (from Mac with esptool.py) -- it seamed successful, updated the % counter of loading, till 100%. See the command, and the output below. So, I then restarted by switching power off, and on (5v to 5v and gnd pin), the blue light flashes once, like normal, but not wirless network, like ESP_0 as per old, where I can connect to it? Also tried Arduino serial monitor, only baud that gives back legible data is 74880, but then I get:

` ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x40100000, len 30112, room 16 
tail 0
chksum 0x2c
load 0x02c6043d, len 1229080576, room 8 
`

btw, the device is a Wemos D1 mini .

`sudo esptool.py --port /dev/cu.wchusbserial1410 write_flash 0x1000 ~/Downloads/firmware_mini.bin
Password:
esptool.py v1.3
Connecting....
Auto-detected Flash size: 32m
Running Cesanta flasher stub...
Wrote 430080 bytes at 0x1000 in 37.1 seconds (92.7 kbit/s)...
Leaving...`

What do you think?

**Comment by psy0rz** [comment]
Strange, which version did you download?

**Comment by jroux1** [comment]
Also did erase flash, it wnet successful, loaded again. Looks like it was the beta, trying the dev bin now.

`sudo esptool.py --port /dev/cu.wchusbserial1410 erase_flash`

**Comment by psy0rz** [comment]
ok let me know how it goes.

**Comment by jroux1** [comment]
Tried to flash with dev 'firmware.bin' as well, also not announcing a wifi network, connected with Arduino serial port, only legible info with 74880 baud, not getting:

`ets_main.c 
 ets Jan  8 2013,rst cause:2, boot mode:(3,7)`

But not interacting at all. Command like reset etc does nothing.

**Comment by psy0rz** [comment]
You can also try using the Arduino IDE: 

Run git clone --recursive https://github.com/letscontrolit/ESPEasy-platformio.git

Then the libraries are in the ESPEasy-platformio/lib dir, and the source code is in the ESPEasy-platformio/src dir. 

After you put them in the usual places, you should be able to compile and upload with Arduino IDE.

**Comment by psy0rz** [comment]
Try resetting it while you are connected to serial. What is the output?

**Comment by psy0rz** [comment]
I tried this with the command you've used on my d1 mini, and it failed as well. I'm currently looking in to it.

**Comment by jroux1** [comment]
Nothing, garble, some characters. I had 147 code, compiled and flashed with Arduindo to the same D1, it is up and running.

**Comment by jroux1** [comment]
Great, thanks.

**Comment by psy0rz** [comment]
try flashing with 0x0 instead of 0x1000. that works here.

I could also use I higher baudrate:

`psy@psypad ~/Downloads % esptool.py -b 1500000 write_flash 0x0 firmware_mini.bin
esptool.py v1.3
Connecting....
Auto-detected Flash size: 32m
Running Cesanta flasher stub...
Flash params set to 0x0040
Wrote 430080 bytes at 0x0 in 5.2 seconds (665.4 kbit/s)...
Leaving...
`

After that connect to serial and reset.

**Comment by jroux1** [comment]
Jip, its working @ 0x0, well done.
