### ISSUE TITLE
flash.cmd needs to be revised for new versioning

### ISSUE THREAD

**Issue by pauly7300** [letscontrolit/ESPEasy-platformio#2]
ESPEasy_R%build%_%fsize%.bin...  The flash.cmd file needs to be updated to accept the new versioning 'v2.0.0...'  Currently it's expecting an R###.

**Comment by psy0rz** [comment]
could you fix it and test if it works, to make sure my firmware layout is correct and works with the parameters used here? perhaps make a pull request as well?

**Comment by BattloXX** [comment]
i have written a small UI in C# for Flashing ESPEasy.
Here are the Binarys and the source Code
https://github.com/BattloXX/ESPEasyFlasher

**Comment by psy0rz** [comment]
thanks! its in v2.0.0-dev3
