### ISSUE TITLE
src and some lib folders don't get included when cloning and must be downloaded separately.  Looks to be a naming issue on the subfolders.

### ISSUE THREAD

**Issue by jefrhi** [letscontrolit/ESPEasy-platformio#3]

**Comment by psy0rz** [comment]
this is indeed an issue and will be solved. the problem is github's way of dealing with submodules.

also dont use this repository, but use this one instead: https://github.com/letscontrolit/ESPEasy

**Comment by psy0rz** [comment]
created new issue https://github.com/letscontrolit/ESPEasy/issues/234
